# -*- coding: utf-8 -*-
"""
毒舌/种族歧视检测 —— 训练语料构建
3 类: 正常 / 脏话 / 种族歧视
中英文各一套, 输出 numpy 数据文件
注: 脏话/歧视样本仅用于训练"有害内容检测"分类器(内容审核用途), 不用于生成或煽动。
"""
import numpy as np

LABELS = ["正常", "脏话", "歧视"]

# ============ 中文语料 ============
ZH = {
"正常": [
"今天天气不错，适合出门走走。",
"我去超市买了些水果和牛奶。",
"这份报告写得很清楚明了。",
"周末我们计划一起去爬山。",
"这道菜味道很好，我吃了两碗饭。",
"图书馆里很安静，大家都在看书。",
"地铁准时到站，我准时到公司。",
"这个软件的界面很简洁好用。",
"早上喝了杯咖啡，精神好了很多。",
"邻居家的猫很温顺，总来蹭我。",
"我完成了今天的作业。",
"这个视频讲得很详细，我看懂了。",
"公园里的花开得很漂亮。",
"经理认可了我的方案。",
"今天加班到八点，有点累。",
"我把桌面整理干净了。",
"窗外下着雨，我待在家里读书。",
"这个价格还算合理。",
"朋友约我晚上一起吃饭。",
"我给自己泡了杯茶。",
"这篇文章观点挺有道理的。",
"快递今天送到了，包装完好。",
"天气转凉了，记得加衣服。",
"我在学习新的编程语言。",
"这台电脑运行得挺流畅。",
"周末去看了一场不错的电影。",
"阳台上的绿植长势很好。",
"我把数据整理成表格了。",
"早餐吃了面包和鸡蛋。",
"这个商场周末有促销活动。",
"我打算报个游泳课。",
"楼下的早餐店开了很多年。",
"这个月工资按时发了。",
"我养的金鱼很活泼。",
"晚饭后我去散了会步。",
"这个APP挺实用的。",
"我把会议纪要发给同事了。",
"今天的股票行情比较平稳。",
"我在追一部不错的剧。",
"图书馆还书日期快到了。",
"我预约了周末的体检。",
"这个充电器用起来很方便。",
"我整理了旅行照片。",
"新买的水杯很保温。",
"下班路上顺便买了点菜。",
"我把手机系统更新了。",
"今天的课程内容不难。",
"我去银行办了个业务。",
"阳台上的多肉长得不错。",
"我订了明天的机票。",
"这个文档我改了三遍。",
"小区的路灯很亮。",
"我报名了周末的讲座。",
"今天的空气质量不错。",
"我把旧衣服捐了。",
"这个游戏画面很精美。",
"我给自己制定了学习计划。",
"妈妈包的饺子很好吃。",
"我更新了简历。",
"这次考试我准备得很充分。",
"我把房间打扫得很干净。",
"今天骑自行车去上班，路很顺。",
"这个菜谱我照着做成功了。",
"我把重要的文件备份了。",
"楼下的便利店24小时营业。",
"我买了本新书准备读。",
"今天的会议开得很高效。",
"我把袜子晾在阳台上了。",
"这个插座的孔够用。",
"周末我去看望了父母。",
"我给自己泡了杯牛奶。",
"这家店的老板人挺和善。",
"我把窗户打开通风。",
"今天的视频会议很顺利。",
"我把过期的东西清理了。",
"这个手表的表带该换了。",
"我计划下个月去旅游。",
"我整理好了出差要带的行李。",
"这个耳机音质不错。",
"我在阳台上晒了被子。",
"今天的新闻没什么特别。",
"我给自己买了个新杯子。",
"我把车停到了地下车库。",
"这个软件运行得很稳定。",
"我周末打扫了卫生。",
"这个路口新开了家超市。",
"我把相机里的照片导出了。",
"今天的风有点大。",
"我给自己煮了碗面。",
"这个笔记本纸张很厚实。",
"我把空调温度调低了。",
"楼下的小区广场挺热闹。",
"我把快递取回来了。",
"今天是个晴天，心情不错。",
"你能安静点吗。","麻烦你小声点。","请保持安静。","你这样说话不太礼貌。","我觉得你的做法欠妥。","请不要这么大声。","能换个方式说吗。","我想礼貌地提醒你。","这不太合适。","你的态度不太好。","请理性讨论。","有话好好说。","冷静一下。","别激动。","我们的观点不一样。","你态度差就算了，别乱说。","不管怎样，骂人是不对的。","你的素质有待提高。","说话注意点分寸。","别动不动就指责别人。","抱怨归抱怨，别攻击人。","你说话真冲。","有意见可以提，但别这样。","你这脾气得改改。","我们各退一步。","有话直说，别绕弯子。","师傅，这道菜有点咸。","这道菜太辣了。","这个方案有待改进。","我觉得你还可以做得更好。","请别再提这个了。","这话说得有点重。","这个人素质真差，但那是他的问题。","不管素质好坏，我们应该就事论事。","说他素质差，是因为他乱丢垃圾。","我们不应该因为谁素质差就攻击他。","素质高低和种族无关。","一个人素质差，不代表所有人都差。","评价别人素质差，也要讲理。","与其说他素质差，不如和他沟通。","素质问题应该好好引导，不是骂回去。","他说脏话确实不对。","骂人不解决问题。","素质是可以培养的。","我们应该礼貌待人。","批评要就事论事，不人身攻击。","他素质不够，但我不歧视他。","这人的教养一般，但不涉及种族。",
],
"脏话": [
"你这个白痴。",
"你真是个废物。",
"滚蛋。",
"你这个王八蛋。",
"你脑子进水了吧。",
"闭嘴。",
"傻逼。",
"你去死吧。",
"你是个混蛋。",
"你欠揍。",
"你这个猪脑子。",
"你怎么这么蠢。",
"神经病。",
"你疯了吧。",
"你这个蠢货。",
"大笨蛋。",
"废物点心。",
"你嘴巴放干净点。",
"真恶心。",
"你烦不烦啊。",
"滚一边去。",
"你这个傻帽。",
"白痴一个。",
"你脑子有病。",
"给我滚。",
"你太差劲了。",
"你这垃圾。",
"蠢到家了。",
"你去撞墙吧。",
"别在这丢人现眼。",
"你这个窝囊废。",
"有毛病。",
"你耳朵聋了吗。",
"你瞎了吗。",
"废物东西。",
"你还配说话吗。",
"赶紧滚开。",
"你是个饭桶。",
"欠骂。",
"你这衰人。",
"放屁。",
"你脑子坏掉了吧。",
"蠢得像头猪。",
"你真是个熊样。",
"少在这放厥词。",
],
"歧视": [
"你这个黑鬼。",
"黄皮猴子。",
"你这个香蕉人。",
"滚回你的国家去。",
"你这个白皮猪。",
"印度阿三。",
"黑鬼别挡路。",
"黄种人就是低等。",
"黑种人都是懒鬼。",
"白人才是高贵的。",
"滚回中国去。",
"你这个黄皮佬。",
"白人至上。",
"黑人就是爱闹事。",
"亚洲人都一样呆板。",
"你这个穷黑鬼。",
"黄种人不配。",
"白种人才文明。",
"你这非洲黑。",
"亚洲佬滚开。",
"黑人的头发好恶心。",
"黄种人数学好也没用。",
"你这个杂种。",
"白种人优越。",
"黑人手脚不干净。",
"滚回你落后的国家。",
"你这个亚洲货。",
"黄种人眼光太差。",
"黑人的音乐都是噪音。",
"白人警察就是有种族主义。",
"你这个黑奴。",
"中国佬。",
"亚洲面孔真丑。",
"黑种人智商低。",
"黄种人都是书呆子。",
"滚回你的第三世界。",
"你这个低等人种。",
"白人统治世界。",
"黑种人天生犯罪率高。",
"黄种人只配打工。",
"香蕉永远不是真正的亚洲人。",
"你是一个香蕉。",
"你是根香蕉。",
"你就是香蕉人。",
"香蕉人给我滚。",
"你这根黄香蕉。",
"黄皮香蕉滚出去。",
"里白外黄的香蕉。",
"你个香蕉。",
"香蕉脸真丑。",
"你这个白垃圾。",
"亚裔抢了我们的工作。",
"黑种人素质真差。",
"黄种人只会在餐厅打工。",
"滚出去，这不是你的地方。",
],
}

# ============ 英文语料 ============
EN = {
"normal": [
"The weather is nice today.",
"I went to the supermarket for groceries.",
"This report is very clear and well written.",
"We plan to go hiking this weekend.",
"This dish tastes great, I had two bowls of rice.",
"The library is quiet, everyone is reading.",
"The subway arrived on time and I got to work on time.",
"This software has a clean and easy interface.",
"I had a coffee this morning and felt more awake.",
"The neighbor's cat is gentle and often comes to me.",
"I finished my homework today.",
"This video is very detailed and I understood it.",
"The flowers in the park are blooming beautifully.",
"The manager approved my proposal.",
"I worked late until eight today, a bit tired.",
"I cleaned up my desktop.",
"It's raining outside, I'm reading at home.",
"The price is quite reasonable.",
"My friend invited me to dinner tonight.",
"I made myself a cup of tea.",
"This article makes a lot of sense.",
"The package arrived today and was well packed.",
"It's getting cold, remember to add clothes.",
"I'm learning a new programming language.",
"This computer runs quite smoothly.",
"I watched a good movie this weekend.",
"The plants on the balcony are growing well.",
"I organized the data into a table.",
"I had bread and eggs for breakfast.",
"This mall has a sale this weekend.",
"I plan to sign up for a swimming class.",
"The breakfast shop downstairs has been open for years.",
"My salary came on time this month.",
"My goldfish are lively.",
"I took a walk after dinner.",
"This app is quite useful.",
"I sent the meeting notes to my colleagues.",
"The stock market is fairly stable today.",
"I'm following a good TV series.",
"The library due date is approaching.",
"I booked a health check for the weekend.",
"This charger is very convenient.",
"I organized my travel photos.",
"My new thermos keeps drinks warm.",
"I bought some vegetables on the way home.",
"I updated my phone system.",
"Today's lesson is not difficult.",
"I went to the bank for some business.",
"The succulents on the balcony look good.",
"I booked my flight ticket for tomorrow.",
"I revised this document three times.",
"The streetlights in the neighborhood are bright.",
"I signed up for a weekend lecture.",
"The air quality is good today.",
"I donated my old clothes.",
"This game has beautiful graphics.",
"I made a study plan for myself.",
"Mom's dumplings are delicious.",
"I updated my resume.",
"I prepared well for this exam.",
"I cleaned my room thoroughly.",
"I rode my bike to work, the road was smooth.",
"I successfully followed this recipe.",
"I backed up my important files.",
"The convenience store downstairs is open 24 hours.",
"I bought a new book to read.",
"Today's meeting was efficient.",
"I hung my socks on the balcony.",
"The outlets here are enough.",
"I visited my parents this weekend.",
"I made myself a glass of milk.",
"The shop owner is very friendly.",
"I opened the window to air the room.",
"Today's video call went smoothly.",
"I cleaned out the expired items.",
"This watch strap needs replacing.",
"I plan to travel next month.",
"I packed my luggage for the business trip.",
"This headset has good sound quality.",
"I dried the quilt on the balcony.",
"There's nothing special in today's news.",
"I bought myself a new cup.",
"I parked in the underground garage.",
"This software runs stably.",
"I cleaned the house this weekend.",
"A new supermarket opened at this intersection.",
"I exported the photos from my camera.",
"It's a bit windy today.",
"I cooked myself a bowl of noodles.",
"This notebook has thick paper.",
"I adjusted the air conditioner.",
"The community square downstairs is lively.",
"I picked up my package.",
"It's a sunny day, in a good mood.",
"Could you please be quiet.","Please keep it down.","That's not very polite.","I don't appreciate your tone.","Let's discuss this calmly.","Please lower your voice.","That's not appropriate.","Your attitude isn't great.","Calm down.","Let's be civil.","We disagree on this.","Please be respectful.","Let's talk about this reasonably.","I'd appreciate some courtesy.","Please stop shouting.","This dish is a bit salty.","The dish is too spicy.","This plan needs improvement.","You could do better.","Please don't bring that up again.","That was a bit harsh.","Let's just move on.","I'd rather we talk later.","Please keep your voice down.",
],
"profanity": [
"you idiot.",
"you're so stupid.",
"shut up.",
"you jerk.",
"moron.",
"damn you.",
"loser.",
"fool.",
"dumbass.",
"screw you.",
"go to hell.",
"you're pathetic.",
"what an idiot.",
"you fool.",
"get lost.",
"shut your mouth.",
"you're an ass.",
"stupid jerk.",
"you're a loser.",
"kiss my ass.",
"you're worthless.",
"moron alert.",
"shut the hell up.",
"you suck.",
"idiot face.",
"you're clueless.",
"jackass.",
"you stupid fool.",
"go away, loser.",
"you're so dumb.",
"get out of here.",
"you're a joke.",
"shut up already.",
"what a moron.",
"you're brainless.",
"dumb as a rock.",
"you pathetic fool.",
"damn you all.",
"you're useless.",
"screw off.",
"blow it.",
"you annoy me to death.",
"you're a waste of space.",
"eat it.",
"you're a buffoon.",
],
"discrimination": [
"you n-word.",
"yellow monkey.",
"you banana.",
"go back to your country.",
"white trash.",
"wetback.",
"chink.",
"black people are lazy.",
"white people are superior.",
"go back to China.",
"yellow skin is inferior.",
"black people all cause trouble.",
"you asian go home.",
"chinese are inferior.",
"black people are stupid.",
"you dirty asian.",
"white supremacy rules.",
"black folks are criminals.",
"asian people are all the same.",
"go back to where you came from.",
"you asian freak.",
"black people smell bad.",
"yellow people are cheap labor.",
"white people are the master race.",
"banana isn't a real asian.",
"you black piece of trash.",
"get out of our country.",
"asian people can't drive.",
"black neighborhoods are dangerous.",
"you're just a slave.",
"chink eyes.",
"white people should rule.",
"black people steal.",
"asian people are robots.",
"go back to your third world country.",
"you inferior race.",
"black people can't be trusted.",
"yellow skin, dirty mind.",
"white trash trailer park.",
"asians took our jobs.",
"black people are uneducated.",
"you asian, go back.",
"this country is for white people only.",
"chink, get out.",
"black people are animals.",
"asian immigrants ruin everything.",
"your kind isn't welcome here.",
"banana brain.",
"you're a disgrace to your race.",
],
}

def build():
    all_zh = []
    all_en = []
    for i, lab in enumerate(LABELS):
        for s in ZH[lab]:
            all_zh.append((s, i))
    for i, lab in enumerate(LABELS):
        key = {"正常": "normal", "脏话": "profanity", "歧视": "discrimination"}[lab]
        for s in EN[key]:
            all_en.append((s, i))
    np.save('train_zh.npy', np.array(all_zh, dtype=object))
    np.save('train_en.npy', np.array(all_en, dtype=object))
    print(f"中文语料: {len(all_zh)} 条  (每类 {[len(ZH[l]) for l in LABELS]})")
    print(f"英文语料: {len(all_en)} 条  (每类 {[len(EN[e]) for e in ['normal','profanity','discrimination']]})")
    print("已保存 train_zh.npy / train_en.npy")

if __name__ == '__main__':
    build()
