# -*- coding: utf-8 -*-
"""
情绪分析 —— 训练语料构建
6 类基本情绪: happy/sad/angry/fearful/surprised/disgusted
中英文各一套句子, 输出 numpy 数据文件供训练
"""
import numpy as np

LABELS = ["快乐", "悲伤", "愤怒", "恐惧", "惊讶", "厌恶"]
LABEL_EN = ["happy", "sad", "angry", "fearful", "surprised", "disgusted"]

# ============ 中文语料 ============
ZH = {
"快乐": [
"我今天太开心了，考试居然得了满分。",
"收到生日礼物，我高兴得跳了起来。",
"和好朋友一起玩，我特别快乐。",
"春天来了，阳光暖洋洋的，心情真好。",
"终于放假了，我兴奋得睡不着觉。",
"妈妈夸我懂事，我心里美滋滋的。",
"中了大奖，我欣喜若狂。",
"看到宝宝第一次学会走路，全家人笑得合不拢嘴。",
"这个惊喜让我幸福得直冒泡。",
"久别重逢的老友，让我满心欢喜。",
"拿到录取通知书那一刻，我乐开了花。",
"和喜欢的人一起看日落，我开心极了。",
"周末去郊游，山清水秀，大家玩得兴高采烈。",
"听到偶像要来开演唱会，我激动得尖叫。",
"今天运气爆棚，一连遇到三件好事，我乐不可支。",
"做完作业冲出家门玩耍，我浑身畅快。",
"生日那天朋友都来了，我快乐得像只小鸟。",
"妈妈做的饭菜香喷喷，我吃得心满意足。",
"考上了理想的学校，我高兴得又蹦又跳。",
"收到期待已久的礼物，我雀跃不已。",
"看到孩子们天真笑脸，我由衷感到幸福。",
"风和日丽的日子，和家人在公园散步，真惬意。",
"我抢到了心仪的球票，兴奋到手舞足蹈。",
"梦想成真的感觉，让人欣喜不已。",
"和小伙伴打篮球赢了，我痛快极了。",
"看到满园花开，我心情格外舒畅。",
"好消息传来，我眉开眼笑。",
"她的一番鼓励让我心里暖洋洋的，格外开心。",
"多年心愿终于达成，我喜极而泣。",
"全家团圆吃年夜饭，我笑得合不拢嘴。",
"听到孩子喊爸爸，我心里乐滋滋的。",
"中了彩票，我高兴得差点原地起飞。",
"今天面试通过，我信心满满又开心。",
"和老同学叙旧，我心情大好。",
"考试超常发挥，我兴奋得直拍大腿。",
"吃到最爱的甜品，我开心得眯起眼睛。",
"看到彩虹挂在天边，我欣喜地欢呼。",
"妈妈奖励我新玩具，我开心得飞起。",
"和队友一起夺冠，我激动得热泪盈眶。",
"清晨鸟鸣花香，我心情舒畅。",
"收到远方朋友的信，我满心欢喜。",
"一切顺利的一天，我心情愉快。",
"她答应了我的请求，我欣喜若狂。",
"今天阳光明媚，我的心情格外好。",
"看到自己的画作获奖，我高兴极了。",
"和朋友分享笑话，我笑得前仰后合。",
"任务圆满完成，我成就感满满，心情超好。",
"久违的晴天，我心情豁然开朗。",
"生日聚会热闹温馨，我过得特别开心。",
"得知外婆身体好转，我悬着的心放下，非常高兴。",
"明天要去旅行了，我兴奋得一晚上没睡好。",
"我的文章被发表了，我欣喜万分。",
"看到满天繁星，我心情特别放松愉悦。",
"终于见到久别的亲人，我激动得热泪盈眶。",
"项目成功上线，全组人都兴高采烈。",
"吃到妈妈做的红烧肉，我幸福极了。",
"获奖的那一刻，我快乐得想大声唱歌。",
"和朋友通宵畅谈，我心里暖烘烘的。",
"小猫咪在我怀里打呼噜，我开心得不行。",
],
"悲伤": [
"宠物去世了，我难过得哭了一整天。",
"和最好的朋友闹翻了，我很伤心。",
"错过了重要的机会，我心里好失落。",
"深夜想起离世的亲人，我泪流满面。",
"考试成绩一塌糊涂，我沮丧极了。",
"一个人漂泊在外，我常常感到孤独和悲伤。",
"心爱的球队输球了，我难过得好久缓不过来。",
"听着悲伤的歌曲，眼泪不自觉流下来。",
"得知这个坏消息，我心如刀割。",
"分手那天，我痛不欲生。",
"看着空荡荡的房间，我一阵心酸。",
"奶奶离开后，我每天都很忧郁。",
"辛苦写的东西被否了，我心里沉甸甸的。",
"一个人过节，我格外失落。",
"毕业各奔东西，我难舍难分，心里难受。",
"听到好友生病的消息，我忧心忡忡，十分难过。",
"努力了那么久还是失败，我心灰意冷。",
"童年的小伙伴都散了，我感慨又惆怅。",
"望着她远去的背影，我满心凄凉。",
"眼泪止不住地往下掉，我心里好苦。",
"生离死别的痛，让我久久无法释怀。",
"梦想破碎的那一刻，我绝望得说不出话。",
"我一个人坐在窗边发呆，心里空落落的。",
"得知计划全泡汤，我失望极了。",
"父母的叹息声，让我心里不是滋味。",
"这世间少了一个爱我的人，我悲痛欲绝。",
"深夜辗转反侧，孤独感把我淹没。",
"我失败了，觉得一切都毫无意义，很沮丧。",
"看着他落寞的背影，我心里酸酸的。",
"再也没有人听我说话了，我好难过。",
"回不去的旧时光，让我怅然若失。",
"病情不见好转，我心情低落到谷底。",
"离别时她哭了，我也忍不住红了眼眶。",
"作品被退稿三次，我几乎要崩溃。",
"孤独像潮水一样涌来，我悲伤得难以自拔。",
"失去挚友，我整天郁郁寡欢。",
"往事历历在目，我忍不住泪湿眼眶。",
"她的离开让我心碎了一地。",
"计划多年的远行泡汤，我满心遗憾。",
"一整天都提不起精神，我心里难过。",
"听到噩耗，我当场泣不成声。",
"望着空落落的家，我悲伤得难以自持。",
"一切都结束了，我心里空空的，很失落。",
"她被病魔折磨，我心疼又难过。",
"分离的痛，像针一样扎在心上。",
"下雨的傍晚，我莫名地感到悲伤。",
"努力全都白费了，我心如死灰。",
"看着老照片，我沉浸在伤感的回忆里。",
"妈妈操劳的背影让我心酸不已。",
"我辜负了大家的期望，心里愧疚又难过。",
"阴雨绵绵的天气，让我的心情也跟着低落。",
"一个人过生日，我特别想哭。",
"日子一天天过去，我却看不到希望，很灰心。",
"他把心事都憋在心里，我替他感到难过。",
"夜深人静时，孤独和悲伤最折磨人。",
"那张合照里的人都散了，我看了很久，心里难受。",
"漂泊多年，我时常感到身心俱疲又悲伤。",
"最爱的小说结局太悲凉，我难过了一晚上。",
"她红着眼眶说再见，我心都碎了。",
],
"愤怒": [
"他怎么可以这样骗我，我气得发抖。",
"有人插队，我火冒三丈。",
"被人冤枉，我愤怒得说不出话。",
"等了半天外卖还没到，我真的生气了。",
"他把我的东西摔坏了，我气坏了。",
"无良商家坑人，我恨不得去投诉。",
"一再被放鸽子，我恼火极了。",
"看到霸凌现场，我怒火中烧。",
"键盘侠乱喷，我气得直拍桌子。",
"这事太气人了，我忍无可忍。",
"他出尔反尔，我恨得牙痒痒。",
"辛苦做的方案被白白窃取，我勃然大怒。",
"对方蛮不讲理，我气冲头顶。",
"又迟到又不道歉，我火大得很。",
"看到虐待小动物，我愤怒得握紧拳头。",
"被无端指责，我憋了一肚子火。",
"他屡教不改，我实在气不过。",
"这种不要脸的发言，我气得浑身发抖。",
"有人破坏规则还洋洋得意，我怒不可遏。",
"被人背后捅刀子，我怒火难消。",
"排队三小时被告知没票，我火冒三丈。",
"他明明错了还死不认账，我气炸了。",
"这种强盗逻辑，让我恼羞成怒。",
"看到垃圾乱扔污染环境，我愤怒不已。",
"服务态度差劲，我气得想投诉。",
"被人当众羞辱，我怒火中烧。",
"他满嘴跑火车，我气得无话可说。",
"这种不负责任的甩锅，让我怒不可遏。",
"我反复叮嘱他还是弄砸了，气死我了。",
"看到欺诈老人的新闻，我义愤填膺。",
"她嘲笑我的努力，我气得牙痒。",
"被人抢先领了功劳，我怒火万丈。",
"这种嚣张的样子，简直让我火冒三丈。",
"等了一个小时还放我鸽子，我气不打一处来。",
"无端被扣钱，我愤怒得想去找说法。",
"听到有人说家乡坏话，我怒上心头。",
"他随手乱扔垃圾还一脸无所谓，我十分生气。",
"这种两面三刀的小人，让我怒火中烧。",
"被人当猴耍，我气得直跺脚。",
"广告夸大其词骗人，我愤愤不平。",
"他打断了我的话还不道歉，我恼火极了。",
"看到有人破坏公物，我怒火冲天。",
"她背后说三道四，我气得发抖。",
"屡次被骚扰，我忍无可忍了。",
"这种无赖行径，简直让人暴跳如雷。",
"我把话说透了还是对牛弹琴，真气人。",
"被人抢了停车位，我气急败坏。",
"他嚣张跋扈的样子，让我怒发冲冠。",
"谎话连篇还振振有词，我愤怒得不行。",
"看到不公义的事，我愤懑难平。",
"我的快递被莫名弄丢，我火大得很。",
"他一次次得寸进尺，我实在愤怒。",
"这种无礼的冒犯，我无法容忍。",
"被人诋毁，我气得浑身发冷。",
"他毁约还反咬一口，我怒不可遏。",
"看到动物被虐待的视频，我怒火攻心。",
"我又被他耍了，气得直咬牙。",
"这种狗眼看人低的嘴脸，让我火冒三丈。",
"等了这么久竟取消航班，我气疯了。",
"他满嘴脏话还倒打一耙，我实在咽不下这口气。",
],
"恐惧": [
"半夜听到奇怪的声响，我吓得不敢动。",
"看恐怖片，我吓得魂飞魄散。",
"独自走夜路，我害怕极了。",
"考试临近，我紧张得手抖。",
"从高处往下看，我吓得腿软。",
"黑暗中有什么东西，我毛骨悚然。",
"明天要当众演讲，我忐忑不安。",
"遇到狂吠的大狗，我惊慌失措。",
"得知要动手术，我恐惧得整晚失眠。",
"飞机遇到气流颠簸，我吓得脸色发白。",
"深夜听到敲门声，我惊出一身冷汗。",
"蛇在脚边爬过，我吓得尖叫着跳开。",
"地震来临，我惊恐万分地跑向空地。",
"第一次坐过山车，我紧张得闭紧眼睛。",
"医院消毒水的气味让我不寒而栗。",
"看到血迹，我吓得倒退两步。",
"一个人被困在电梯里，我恐惧极了。",
"雷雨交加的夜晚，我吓得缩进被窝。",
"迷路在陌生的地方，我心惊胆战。",
"得知有危险，我吓得立刻逃开。",
"黑暗中的脚步声越来越近，我恐惧得屏住呼吸。",
"站在悬崖边，我双腿发软，惊恐万分。",
"突如其来的巨响，把我吓得浑身一颤。",
"被抓包的那一刻，我心虚又害怕。",
"听到恐怖传闻，我毛骨悚然。",
"独自在荒山过夜，我胆战心惊。",
"濒临溺水的瞬间，我恐惧到了极点。",
"看到狰狞的面孔，我吓得魂不附体。",
"明知是幻觉还是害怕，我浑身发抖。",
"被恶梦惊醒，我一身冷汗，惊魂未定。",
"深夜接到的电话让我心惊肉跳。",
"面对凶猛的野兽，我吓得不敢呼吸。",
"得知亲人出事，我惊恐得瘫坐在地。",
"闪电劈下那一刻，我吓得抱头蹲下。",
"坐过山车到最高点，我吓得大叫。",
"黑暗里有什么在动，我恐惧得不敢睁眼。",
"被骗进危险境地，我吓得六神无主。",
"高楼电梯突然停电，我惊慌失措。",
"独自漂流在海上，我恐惧得发抖。",
"眼前的黑影让我毛骨悚然。",
"听到孩子的哭声在空楼里回荡，我吓得汗毛倒竖。",
"第一次上台，我紧张得忘了词。",
"被狗追着跑，我吓得魂飞魄散。",
"深夜独处听到异响，我心惊胆战。",
"攀登陡峭岩壁，我恐惧得腿脚发软。",
"遇到暴风雨，我惊恐万分。",
"黑暗中摸索前行，我害怕极了。",
"得知病情恶化，我恐惧得整夜无眠。",
"被人跟踪的感觉让我毛骨悚然。",
"车失控的瞬间，我吓得尖叫。",
"被关在黑屋子里，我恐惧到极点。",
"面对发疯的人群，我吓得躲到角落。",
"听说山里闹鬼，我一个人不敢去。",
"水中突然出现动静，我吓得往后退。",
"深夜独自在家，我总疑神疑鬼，心里发慌。",
"看到倒地的路人一动不动，我吓得魂不守舍。",
"马上就要大考，我紧张得心跳加速。",
"电梯摇晃的那一刻，我惊恐万状。",
"听到楼上传来诡异的声音，我毛骨悚然。",
"在陌生的深林里走失，我恐惧得几乎崩溃。",
],
"惊讶": [
"没想到你这么厉害，我惊呆了。",
"这个消息太突然了，简直不可思议。",
"他居然辞职了，我大为惊讶。",
"你竟然还记得这件事，我震惊得说不出话。",
"天啊，这里也太美了吧，我目瞪口呆。",
"忽然看到多年未见的老朋友，我愣在原地。",
"结果完全出乎我的意料，太意外了。",
"这件事反转太快，我瞠目结舌。",
"你怎么做到的，我简直不敢相信。",
"他居然说走就走，我大为震惊。",
"中奖消息传来，我难以置信。",
"这个真相让我惊讶得合不拢嘴。",
"她居然拒绝了，我万万没想到。",
"看到他把字写得这么好，我眼前一亮，十分意外。",
"比赛结果出乎所有人的预料，全场哗然。",
"得知他是隐藏的大佬，我惊得说不出话来。",
"这蛋糕居然是纸做的，我大吃一惊。",
"你居然会这个，太让人意外了。",
"一觉醒来窗外全是雪，我惊喜万分。",
"他突然求婚，我惊讶得呆住了。",
"没想到老板还记得我的名字，我很惊讶。",
"这个数据颠覆了我的认知，我难以置信。",
"他居然为了我放弃了机会，我大为感动又惊讶。",
"看到我的画被展出，我惊喜不已。",
"真相大白那一刻，我目瞪口呆。",
"她竟然主动来道歉，我受宠若惊。",
"这只小猫居然会开门，我惊讶极了。",
"他轻轻松松跑完马拉松，我惊得合不拢嘴。",
"没想到这里藏着这么美的地方，我惊叹不已。",
"你居然一夜之间写完报告，我难以置信。",
"结局的反转让我惊讶得瞪大眼睛。",
"他平时那么安静，居然还会跳舞，我太意外了。",
"这个发明太神奇了，我大开眼界。",
"得知自己拿了第一名，我惊讶得说不出话。",
"眼前的景象太出乎意料，我目瞪口呆。",
"她居然还记得我的生日，我惊喜交加。",
"看到陌生人帮助了我，我十分意外。",
"那本书的作者竟是他，我震惊不已。",
"突然停电又来电，我吓了一跳。",
"原本以为会输，结果赢了，我惊喜万分。",
"他病好了，我难以置信又高兴。",
"没想到门背后还有个大院子，我大为惊讶。",
"这个彩蛋藏得太深，我惊奇不已。",
"她比我高一个头，我见到时很惊讶。",
"他居然在雨天跑来见我，我受宠若惊。",
"谜底揭开时，我恍然大悟，十分惊讶。",
"一百岁的爷爷还会用手机，我惊叹连连。",
"他一张口就惊艳全场，我目瞪口呆。",
"得知这栋楼是空的，我惊出一身冷汗又意外。",
"你的进步太快了，我惊叹不已。",
"他居然是我失散多年的亲戚，我震惊得说不出话。",
"看到会发光的植物，我惊奇极了。",
"这个项目他一个人就搞定了，我难以置信。",
"你家的狗居然会算术，我惊讶得说不出话。",
"他一句外语也不会，却独自去了国外，我大为震惊。",
"没想到你是这样的人，我一直看走眼了，很惊讶。",
"听到这个秘密，我惊讶得捂住了嘴。",
"她居然把所有家当都捐了，我震惊不已。",
"原本以为今天下雨，结果晴空万里，我喜出望外。",
"他三天就把书背完了，我惊得合不拢嘴。",
"真相是我万万没想到的，我惊讶得久久说不出话。",
],
"厌恶": [
"这味道太恶心了，我想吐。",
"看到苍蝇落在食物上，我嫌恶地皱眉。",
"他满口谎言，我特别反感。",
"这种虚伪的人，我厌恶极了。",
"地上黏糊糊的东西，让我作呕。",
"他得意洋洋的样子，真让人讨厌。",
"这菜又咸又腻，我嫌弃地放下筷子。",
"跟这种小气鬼打交道，真烦人。",
"那恶心的虫子爬来爬去，我浑身起鸡皮疙瘩。",
"看到他假惺惺的笑，我就恶心。",
"这种势利眼，我打心底反感。",
"闻起来像馊了的味道，我嫌弃地捂住鼻子。",
"他说话时口水乱喷，我很厌恶。",
"这种阿谀奉承的嘴脸，真让人作呕。",
"黏糊糊的鼻涕虫，我恶心坏了。",
"满桌的油腻让我毫无胃口，很反感。",
"他的虚伪做作，我讨厌至极。",
"这种背地里说人坏话的行为，我深恶痛绝。",
"看到老鼠，我恶心又害怕。",
"这种自以为是的口吻，我十分反感。",
"一股恶臭扑面而来，我干呕起来。",
"他踩到狗屎还浑然不觉，我嫌恶地后退。",
"这种落井下石的行为，真让人作呕。",
"看他对下属颐指气使，我反感透了。",
"腐臭的垃圾堆让我作呕。",
"他满嘴跑火车还沾沾自喜，我十分厌恶。",
"这种幸灾乐祸的人，我讨厌得不行。",
"黏腻的触感让我浑身起鸡皮疙瘩。",
"这种两面派嘴脸，我深恶痛绝。",
"他舔盘子的样子，我看了想吐。",
"这种粗俗的玩笑，让人反感。",
"满身烟味熏得我难受，我避之不及。",
"他那谄媚的笑让我恶心。",
"这种占小便宜还炫耀的人，我十分讨厌。",
"呕吐物的气味让我胃里翻江倒海。",
"他随手扔垃圾的行为让我厌恶。",
"这种幸灾乐祸的嘴脸，真叫人作呕。",
"地上蠕动的虫子让我反感极了。",
"这种假大空的发言，我听着就烦。",
"他一边夸人一边踩人，真让人厌恶。",
"油腻的桌面让我嫌弃地皱起眉。",
"这种背信弃义的小人，我深恶痛绝。",
"他的表演欲太强，我看着就反感。",
"一股腥味飘来，我恶心地捂住口鼻。",
"他随地吐痰的样子，真让人讨厌。",
"这种攀比炫耀的朋友圈，我看着就烦。",
"黏糊糊的果酱弄了一手，我嫌恶地擦掉。",
"这种溜须拍马的嘴脸，我打心底作呕。",
"垃圾堆里爬出的虫子让我毛骨悚然又厌恶。",
"他那种高人一等的语气，真让人反感。",
"这种无休止的抱怨，我听着就烦。",
"看着他那虚伪的面具，我恶心得不行。",
"一股酸臭味袭来，我作呕地远离。",
"他厚颜无耻的样子让我厌恶至极。",
"这种损人不利己的行为，真让人反感。",
"他吃东西吧唧嘴的声音，我听了就厌恶。",
"这种当面一套背后一套的人，我深恶痛绝。",
"油腻腻的剩菜让我毫无食欲，还很嫌弃。",
"他那副阿谀谄媚的嘴脸，真叫我作呕。",
"看到满地的黏稠污物，我恶心坏了。",
],
}

# ============ 英文语料 ============
EN = {
"happy": [
"I'm so happy I got full marks on the exam.",
"I jumped for joy when I got the birthday present.",
"I feel great playing with my best friends.",
"The warm spring sunshine makes me feel wonderful.",
"I'm so excited I can't sleep now that the holiday is here.",
"Mom praised me and I feel on top of the world.",
"I hit the jackpot and I'm over the moon.",
"We all beamed with joy when the baby took his first steps.",
"This surprise makes me feel so blessed.",
"Reuniting with my old friend filled me with delight.",
"I was overjoyed when the acceptance letter arrived.",
"I feel thrilled watching the sunset with someone I love.",
"The weekend trip was wonderful, everyone was cheerful.",
"I screamed with excitement when my idol announced a concert.",
"Today is my lucky day, I'm absolutely ecstatic.",
"Running out to play after homework, I feel so free and happy.",
"All my friends came to my birthday, I was overjoyed.",
"Mom's cooking is delicious and I feel content.",
"I was hopping with happiness when I got into my dream school.",
"I received my long-awaited gift and I'm delighted.",
"The children's innocent smiles make me truly happy.",
"A beautiful sunny day with family in the park, so lovely.",
"I grabbed the tickets I wanted, I'm thrilled.",
"Making my dream come true feels amazing.",
"We won the basketball game and I feel ecstatic.",
"The garden full of flowers lifts my spirits.",
"Great news, I'm grinning from ear to ear.",
"Her encouragement warmed my heart and made me happy.",
"My long-held wish finally came true, I wept with joy.",
"The whole family reunited for dinner, everyone was smiling.",
"Hearing my child call me, I felt a surge of happiness.",
"I won the lottery and nearly floated away with joy.",
"My interview went well, I'm confident and happy.",
"Catching up with old classmates, my mood is wonderful.",
"I aced the test and I'm thrilled to bits.",
"Eating my favorite dessert made me beam.",
"The rainbow in the sky made me cheer with joy.",
"Mom rewarded me with a new toy and I'm ecstatic.",
"We won the championship together, I was moved to tears.",
"The birds singing this morning lift my spirits.",
"Receiving a letter from afar filled me with joy.",
"It's been a smooth, happy day all around.",
"She said yes to my request, I'm ecstatic.",
"The bright sunshine puts me in a wonderful mood.",
"Seeing my painting win an award made me so happy.",
"Sharing jokes with friends, I laughed until I hurt.",
"Finishing the task gave me great satisfaction and joy.",
"The long-awaited sunny day lifted my mood.",
"My birthday party was warm and fun, I had a great time.",
"Hearing grandma recovered, I was relieved and happy.",
"I'm so excited about the trip tomorrow I couldn't sleep.",
"My article got published, I'm overjoyed.",
"Seeing the starry sky, I feel relaxed and joyful.",
"Finally seeing my family again, I was moved to tears.",
"The project launched successfully, everyone was thrilled.",
"Eating mom's braised pork made me feel so happy.",
"The moment I won the award, I wanted to sing.",
"Talking all night with friends warmed my heart.",
"The kitten purring in my arms makes me so happy.",
],
"sad": [
"My pet died and I cried all day.",
"Falling out with my best friend makes me very sad.",
"Missing the big chance, I feel disappointed.",
"I wept thinking of my departed relative late at night.",
"My exam results were terrible, I'm so depressed.",
"Living alone far from home, I often feel lonely and sad.",
"My favorite team lost and I was down for a long time.",
"Listening to sad songs, tears fell without control.",
"Learning the bad news, I felt heartbroken.",
"The day of the breakup, I was in agony.",
"Looking at the empty room, I felt a pang of sorrow.",
"Ever since grandma passed, I've been melancholy.",
"My hard work was rejected, my heart feels heavy.",
"Being alone during the festival makes me so lonely.",
"Graduation scattered us apart, I felt awful.",
"Hearing my friend is sick, I'm worried and sad.",
"I tried so hard yet failed, I feel disheartened.",
"Childhood friends have all gone, I feel wistful.",
"Watching her walk away, my heart was full of grief.",
"Tears kept falling, my heart feels so bitter.",
"The pain of parting and death lingers in my heart.",
"The moment my dream shattered, I was speechless with despair.",
"I sat by the window, my heart feeling empty.",
"Learning the plan collapsed, I was deeply disappointed.",
"My parents' sighs made me feel uneasy.",
"The world lost someone who loved me, I'm devastated.",
"Tossing and turning at night, loneliness drowns me.",
"I failed and everything feels meaningless, I'm dejected.",
"Seeing his lonely back, my heart ached.",
"No one listens to me anymore, I'm so sad.",
"The irretrievable past leaves me wistful.",
"My illness isn't improving, my spirits hit rock bottom.",
"She cried at the farewell, and I couldn't hold back tears.",
"My work was rejected three times, I almost broke down.",
"Loneliness floods in like a tide, I can't escape my sadness.",
"Losing my closest friend, I mope all day.",
"Memories flood back and tears wet my eyes.",
"Her leaving broke my heart into pieces.",
"The long-planned trip fell through, I'm full of regret.",
"I can't muster any energy all day, my heart is heavy.",
"Hearing the terrible news, I sobbed uncontrollably.",
"Looking at the empty home, I can't contain my grief.",
"It's all over, my heart feels hollow and lost.",
"She suffers from illness and I feel so sorry for her.",
"The pain of separation stings like a needle in my heart.",
"On a rainy evening, I feel sad for no reason.",
"All my effort was in vain, my heart is ashes.",
"Looking at old photos, I sink into melancholy memories.",
"Mom's tired back makes my heart ache.",
"I let everyone down, I feel guilty and sad.",
"The drizzling weather drags my mood down.",
"Spending my birthday alone, I really want to cry.",
"Days pass but I see no hope, I feel despair.",
"He keeps his worries inside, and I feel sad for him.",
"In the dead of night, loneliness and sadness torment me most.",
"I stared at the photo of people who've scattered, feeling sad.",
"Years of drifting make me weary and sorrowful.",
"The novel's tragic ending made me sad all night.",
"She said goodbye with red eyes and my heart broke.","I'm sad that my flight got cancelled.","My flight was cancelled and I'm upset.","I was so disappointed when I missed the train.","Getting rejected from the job made me really sad.","The team lost the final game and I felt down.","Breaking up with her crushed me.","My phone broke and I lost all my photos.","Raining on my birthday made me sad.","I failed the driving test again, so frustrating.","Nobody remembered my birthday, I felt lonely.","She ignored my message all day, that hurt.","I had to put my old dog down, heartbroken.","Losing my wallet on the bus was upsetting.","The hospital called with bad news about my dad.","My best friend moved away and I miss her.","Missing the deadline was really disappointing.","I burned the dinner and ruined the whole meal.","Getting a flat tire on the highway stressed me out.","The concert got cancelled and I was bummed.","I lost my keys again and I feel stupid.","Waiting for hours in the rain made me miserable.","The test result was worse than I expected, so sad.","I don't fit in anywhere, I feel lonely and sad.","They laughed at my drawing and I felt hurt.","I'm grieving the loss of my childhood home.","My savings were wiped out and I'm devastated.","The plants I cared for all died, so upsetting.",
],
"angry": [
"How could he lie to me like that, I'm shaking with anger.",
"Someone cut in line and I'm furious.",
"Being wrongly accused, I was too angry to speak.",
"Waiting ages for food that never came, I got really angry.",
"He broke my things and I'm livid.",
"The dishonest merchant cheated me, I want to complain.",
"Being stood up again and again, I'm fuming.",
"Seeing bullying happen, I was burning with rage.",
"The trolls online made me slam the table in anger.",
"This is outrageous, I can't take it anymore.",
"He broke his word, I'm gritting my teeth with rage.",
"Someone stole my hard work and I flew into a rage.",
"The other party is unreasonable, I'm boiling with fury.",
"He's late again without apologizing, I'm seething.",
"Seeing animals mistreated, I clenched my fists in anger.",
"Being blamed for nothing, I have a belly full of fire.",
"He never learns, I really can't bear it.",
"That shameless remark made me tremble with rage.",
"Seeing someone break rules proudly, I'm furious.",
"Being stabbed in the back, my anger won't fade.",
"After queuing three hours I was told no tickets, I'm mad.",
"He's clearly wrong yet refuses to admit it, I'm livid.",
"That twisted logic makes me furious.",
"Seeing people litter and pollute, I'm angry.",
"The terrible service made me want to complain.",
"Being humiliated in public, I burned with rage.",
"He talks nonsense and I'm speechless with anger.",
"That irresponsible blame-shifting makes me furious.",
"Despite my warnings he ruined it, I'm mad as hell.",
"Seeing news of people scamming the elderly, I'm outraged.",
"She mocked my effort and I gritted my teeth.",
"Someone took credit for my work, I'm furious.",
"That arrogant attitude makes me see red.",
"Waiting an hour to be stood up, I was fit to be tied.",
"Being charged unfairly, I wanted to demand answers.",
"Hearing someone badmouth my hometown, I felt angry.",
"He littered and acted like it was nothing, I'm annoyed.",
"Such a two-faced person makes me furious.",
"Being made a fool of, I stamped my feet in anger.",
"The exaggerated ads fool people, I'm indignant.",
"He interrupted me and didn't apologize, I'm mad.",
"Seeing someone damage public property, I'm furious.",
"She gossips behind my back, I'm shaking with rage.",
"Harassed again and again, I've had enough.",
"Such shameless behavior makes me boil over.",
"I spelled it out and he still ignored me, so annoying.",
"Someone stole my parking spot, I'm furious.",
"His domineering manner makes me livid.",
"Lying through his teeth and acting proud, I'm furious.",
"Seeing injustice, my anger won't subside.",
"My package got lost somehow, I'm angry.",
"He keeps pushing his luck, I'm really mad.",
"Such rude intrusion is intolerable.",
"Being slandered, I feel cold with rage.",
"He broke the deal and blamed me, I'm furious.",
"Watching an animal cruelty video, I'm raging.",
"He tricked me again, I'm grinding my teeth.",
"That condescending attitude makes me furious.",
"Waiting so long only to cancel the flight, I'm going crazy.",
"He curses and twists the story, I can't swallow this anger.",
],
"fearful": [
"I heard a strange sound at midnight and froze in fear.",
"Watching a horror movie, I was scared out of my wits.",
"Walking alone on a dark road, I'm terrified.",
"The exam is near and I'm shaking with nerves.",
"Looking down from high up, my legs went weak with fear.",
"Something lurks in the dark, sending chills down my spine.",
"I have to give a speech tomorrow, I'm very anxious.",
"Facing a barking dog, I panicked.",
"Learning I need surgery, I was so afraid I couldn't sleep.",
"The plane hit turbulence and I turned pale with fear.",
"Hearing a knock at the door at night, I broke into a cold sweat.",
"A snake crawled by my feet and I screamed and jumped back.",
"When the earthquake hit, I ran to the open in terror.",
"Riding a roller coaster for the first time, I shut my eyes in fear.",
"The smell of the hospital makes me uneasy and afraid.",
"Seeing blood, I stepped back in fright.",
"Stuck alone in an elevator, I was terrified.",
"On a stormy night, I hid under the blanket in fear.",
"Getting lost in a strange place, I was full of dread.",
"Hearing about the danger, I fled in fear.",
"The footsteps in the dark came closer and I held my breath.",
"Standing at the cliff's edge, my legs trembled with terror.",
"A sudden loud noise made me jump in fright.",
"Being caught, I felt guilty and scared.",
"Hearing a frightening rumor, chills ran down my spine.",
"Spending the night alone on a wild mountain, I was terrified.",
"Nearly drowning, I was scared to death.",
"Seeing a scary face, I was frightened out of my mind.",
"I know it's a hallucination but I'm still shaking.",
"Waking from a nightmare, I was drenched in cold sweat.",
"The late-night phone call made my heart pound.",
"Facing a fierce beast, I dared not breathe.",
"Hearing my family was in danger, I collapsed in terror.",
"The lightning strike made me duck and cover in fear.",
"At the roller coaster's peak, I screamed in fear.",
"Something moved in the dark and I was too scared to open my eyes.",
"Lured into a dangerous place, I was beside myself with fear.",
"The elevator stopped suddenly, I panicked.",
"Drifting alone at sea, I trembled with fear.",
"The shadow before me sent chills down my spine.",
"Hearing a child's cry echo in an empty building, my hair stood on end.",
"Going on stage for the first time, I froze and forgot my lines.",
"Chased by a dog, I ran for my life in fear.",
"Alone at night, a strange noise made my blood run cold.",
"Climbing the steep cliff, my legs turned to jelly.",
"Caught in a violent storm, I was terrified.",
"Groping in the dark, I was scared stiff.",
"Learning my illness got worse, I couldn't sleep all night.",
"Feeling followed, I got chills down my spine.",
"The moment the car spun out, I screamed in terror.",
"Locked in a dark room, I was terrified.",
"Facing a raging crowd, I hid in a corner in fear.",
"Rumors of ghosts in the mountain kept me from going alone.",
"Something splashed in the water and I backed away.",
"Home alone at night, I'm jumpy and on edge.",
"Seeing someone lying motionless, I was scared out of my wits.",
"The big exam is tomorrow and my heart is racing.",
"The elevator shook and I was panic-stricken.",
"Eerie sounds from upstairs made my skin crawl.",
"Lost deep in a strange forest, I was on the verge of despair.",
],
"surprised": [
"I never expected you to be so good, I'm amazed.",
"The news came out of nowhere, it's unbelievable.",
"He actually quit his job, I'm stunned.",
"You actually remembered this, I'm shocked speechless.",
"Oh my, this place is gorgeous, I'm dumbfounded.",
"Seeing an old friend suddenly, I froze in place.",
"The result totally defied my expectations, so unexpected.",
"The plot twist came too fast, I was left gaping.",
"How did you do that, I can't believe it.",
"He just up and left, I'm astonished.",
"Winning the prize, I couldn't believe my ears.",
"This truth left me too shocked to close my mouth.",
"She actually refused, I never saw that coming.",
"Seeing how beautifully he writes, I was pleasantly surprised.",
"The result shocked the whole crowd, everyone gasped.",
"Finding out he's the hidden expert, I was speechless.",
"This cake is made of paper, I was astonished.",
"You know how to do this, what a surprise.",
"Waking to a world of snow, I was thrilled.",
"He proposed out of the blue, I froze in surprise.",
"I didn't expect the boss to remember my name, I was surprised.",
"This data overturned everything I knew, I can't believe it.",
"He gave up the chance for me, I'm moved and surprised.",
"Seeing my painting displayed, I was delighted and surprised.",
"The truth came out and I was dumbfounded.",
"She actually apologized first, I'm flattered.",
"This kitten can open doors, amazing.",
"He ran a marathon with ease, I was floored.",
"Finding such a beautiful place hidden here, I'm amazed.",
"You finished the report overnight, unbelievable.",
"The twist ending made my eyes pop.",
"He's so quiet yet he can dance, what a surprise.",
"This invention is amazing, my mind is blown.",
"Learning I got first place, I was speechless.",
"The scene before me was so unexpected, I stared in shock.",
"She remembered my birthday, I'm pleasantly surprised.",
"A stranger helped me, how unexpected.",
"Finding out he wrote that book, I'm stunned.",
"The power went out and came back suddenly, I jumped.",
"Thought we'd lose, but we won, I'm overjoyed.",
"He recovered, I can't believe it and I'm relieved.",
"Didn't expect a big courtyard behind the door, what a surprise.",
"This easter egg is hidden deep, I'm astonished.",
"She's a head taller than me, I was surprised to see it.",
"He came to see me in the rain, I'm flattered.",
"When the answer came out, I was amazed.",
"Grandpa at 100 can still use a phone, incredible.",
"He stunned the whole room the moment he spoke.",
"Finding out the building is empty, I was shocked.",
"Your progress is amazing, I'm in awe.",
"He turned out to be my long-lost relative, I was speechless.",
"Seeing plants that glow, I was astonished.",
"He built this project alone, unbelievable.",
"Your dog can do arithmetic, I'm amazed.",
"He went abroad alone without a word of the language, shocking.",
"Didn't expect you to be like this, I misjudged, I'm surprised.",
"Hearing the secret, I covered my mouth in surprise.",
"She donated everything she owned, I'm shocked.",
"Thought it would rain, but it's sunny, I'm pleasantly surprised.",
"He memorized the book in three days, I was floored.",
"The truth was the last thing I expected, I was speechless.",
],
"disgusted": [
"This smell is revolting, I want to throw up.",
"Seeing a fly land on the food, I frowned in disgust.",
"He lies all the time, I find him repulsive.",
"I loathe such hypocritical people.",
"The sticky thing on the ground makes me sick.",
"His smug expression is so annoying.",
"This dish is greasy and bland, I put my chopsticks down in disgust.",
"Dealing with such a stingy person is so tiresome.",
"The disgusting bug crawling around gives me goosebumps.",
"Seeing his fake smile makes me sick.",
"Such snobbish people, I loathe from the bottom of my heart.",
"It smells like it's gone bad, I covered my nose in disgust.",
"The way he sprays saliva when talking disgusts me.",
"Such flattering, bootlicking manners make me want to vomit.",
"The slimy slug disgusts me completely.",
"The greasy table ruined my appetite, I'm put off.",
"His hypocrisy and pretense make me sick.",
"Gossiping behind people's backs disgusts me to the core.",
"Seeing a rat, I was disgusted and scared.",
"That self-righteous tone really turns me off.",
"A foul stench hit me and I gagged.",
"He stepped in dog poop and didn't notice, I recoiled in disgust.",
"Kicking someone when they're down, that's disgusting.",
"Seeing him boss around his subordinates disgusts me.",
"The rotten trash pile makes me nauseous.",
"He talks nonsense and gloats, I find him repulsive.",
"Such gleeful, mean-spirited people, I can't stand them.",
"The slimy touch gives me goosebumps.",
"That two-faced attitude disgusts me deeply.",
"The way he licks his plate made me want to gag.",
"Such vulgar jokes are distasteful.",
"The heavy smoke stinks and I avoid it.",
"That fawning smile of his is nauseating.",
"People who gloat over small gains disgust me.",
"The smell of vomit makes my stomach churn.",
"His littering habits disgust me.",
"That spiteful look on his face is revolting.",
"The crawling worms on the ground repulse me.",
"Such hollow, grandiose talk annoys me.",
"He praises you while stepping on you, how sickening.",
"The greasy table made me frown in disgust.",
"Such a treacherous person, I loathe him.",
"His attention-seeking is off-putting.",
"A fishy smell wafted over and I covered my nose in disgust.",
"Spitting on the ground, how gross.",
"Friends who brag and compare, I find them annoying.",
"The sticky jam on my hand, I wiped it off in disgust.",
"That sycophantic attitude makes me nauseous.",
"The bugs crawling from the trash gave me the creeps.",
"His condescending tone really turns me off.",
"Endless complaining makes me annoyed.",
"Looking at his mask of hypocrisy, I'm sick of it.",
"A sour smell hit me and I backed away in disgust.",
"His shamelessness disgusts me to no end.",
"Harming others for no gain, how disgusting.",
"The way he slurps when eating disgusts me.",
"Such two-faced people, I loathe them.",
"The greasy leftovers killed my appetite.",
"That flattering, fawning look makes me want to puke.",
"Seeing the sticky filth everywhere, I'm revolted.",
],
}

def build():
    all_zh = []
    all_en = []
    for i, lab in enumerate(LABELS):
        for s in ZH[lab]:
            all_zh.append((s, i))
        for s in EN[LABEL_EN[i]]:
            all_en.append((s, i))
    np.save('train_zh.npy', np.array(all_zh, dtype=object))
    np.save('train_en.npy', np.array(all_en, dtype=object))
    print(f"中文语料: {len(all_zh)} 条  (每类 {[len(ZH[l]) for l in LABELS]})")
    print(f"英文语料: {len(all_en)} 条  (每类 {[len(EN[e]) for e in LABEL_EN]})")
    print("已保存 train_zh.npy / train_en.npy")

if __name__ == '__main__':
    build()
